// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShop.Db;

namespace OnlineShop.Db.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240603231648_AddPaintingOrder")]
    partial class AddPaintingOrder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineShop.Db.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = new Guid("56509768-29a5-4bdf-ada5-66e40a06b2b7"),
                            ProductId = new Guid("ac80a1ac-4c7b-4662-8aac-f14a5a90b957"),
                            Url = "/images/goods/image1.jpg"
                        },
                        new
                        {
                            Id = new Guid("d096d5aa-159a-442c-8507-e4449cb78376"),
                            ProductId = new Guid("0122481d-10e3-4b58-89ee-c72269d5c95e"),
                            Url = "/images/goods/image2.jpg"
                        },
                        new
                        {
                            Id = new Guid("d4571918-a7ec-4361-ba2b-8b04ec88ad5b"),
                            ProductId = new Guid("c60de567-a236-4f59-bc76-4aa1109545d6"),
                            Url = "/images/goods/image3.jpg"
                        },
                        new
                        {
                            Id = new Guid("fd4ad9ce-2b57-4abb-9330-6e7ca265b688"),
                            ProductId = new Guid("37acd775-ee3a-4e6d-83c2-3458adcbf87f"),
                            Url = "/images/goods/image4.jpg"
                        },
                        new
                        {
                            Id = new Guid("d720a522-4957-4a50-af7a-8edee651f53c"),
                            ProductId = new Guid("21b68580-8f57-45a4-a415-1ccfa97337c3"),
                            Url = "/images/goods/image5.jpg"
                        },
                        new
                        {
                            Id = new Guid("99a13c69-060e-4663-a6a4-8490630bd027"),
                            ProductId = new Guid("0bc0cbd7-de40-46bd-8133-59c8a35b2761"),
                            Url = "/images/goods/image6.jpg"
                        });
                });

            modelBuilder.Entity("OnlineShop.Db.Models.ImagePainting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PaintingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PaintingId");

                    b.ToTable("ImagesPaintings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("26a8e059-69bc-47ac-93fd-7f75715d8f82"),
                            PaintingId = new Guid("01e5de59-7e9d-4985-9fb9-84e67fbbbdfe"),
                            Url = "/images/paintings/image1.jpg"
                        },
                        new
                        {
                            Id = new Guid("8e913665-4107-40c2-bc31-be6bc537d14d"),
                            PaintingId = new Guid("dc00811d-5c83-4bff-ab04-e10f56dc4faf"),
                            Url = "/images/paintings/image2.jpg"
                        },
                        new
                        {
                            Id = new Guid("2fcbeb71-e0bd-49dd-9643-5b7c6b07b993"),
                            PaintingId = new Guid("2bee2bc7-3a2b-49ed-a608-c24d2d3eecec"),
                            Url = "/images/paintings/image3.jpg"
                        },
                        new
                        {
                            Id = new Guid("bb9e2489-d497-4113-8fd3-1d9398524d04"),
                            PaintingId = new Guid("158cbcb3-cd2b-4a27-bafd-e1c026e97dc0"),
                            Url = "/images/paintings/image4.jpg"
                        },
                        new
                        {
                            Id = new Guid("89152783-b7eb-4ee1-be08-d2b1e44ae58d"),
                            PaintingId = new Guid("fb352635-60db-40cf-8f87-6a94a1355e49"),
                            Url = "/images/paintings/image5.jpg"
                        },
                        new
                        {
                            Id = new Guid("86ace72f-e08c-42ab-8fb6-13abb11ea178"),
                            PaintingId = new Guid("2d6334d7-8965-450e-8c37-741031080e31"),
                            Url = "/images/paintings/image6.jpg"
                        });
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOrder")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Painting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Paintings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01e5de59-7e9d-4985-9fb9-84e67fbbbdfe"),
                            Description = "Холст. Масло. 20х25 см. 2022 г.",
                            Name = "Пряный аромат"
                        },
                        new
                        {
                            Id = new Guid("dc00811d-5c83-4bff-ab04-e10f56dc4faf"),
                            Description = "Холст. Масло. 40х60 см. 2021 г.",
                            Name = "Северное сияние"
                        },
                        new
                        {
                            Id = new Guid("2bee2bc7-3a2b-49ed-a608-c24d2d3eecec"),
                            Description = "Холст. Масло. 20х25 см. 2023 г.",
                            Name = "Городская эстетика"
                        },
                        new
                        {
                            Id = new Guid("158cbcb3-cd2b-4a27-bafd-e1c026e97dc0"),
                            Description = "Холст. Масло. 20х25 см. 2023 г.",
                            Name = "Балерина"
                        },
                        new
                        {
                            Id = new Guid("fb352635-60db-40cf-8f87-6a94a1355e49"),
                            Description = "Холст. Масло. 50х60. 2021 г.",
                            Name = "Важный матч"
                        },
                        new
                        {
                            Id = new Guid("2d6334d7-8965-450e-8c37-741031080e31"),
                            Description = "Холст. Масло. 40х60 см. 2022 г.",
                            Name = "Зимний вечер"
                        });
                });

            modelBuilder.Entity("OnlineShop.Db.Models.PaintingOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalRequest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorPalette")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateOrder")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaintingSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaintingTheme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaintingOrder");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ac80a1ac-4c7b-4662-8aac-f14a5a90b957"),
                            Cost = 400m,
                            Description = "Набор гуаши 5 цветов, художественная 40 мл.",
                            Name = "Гуашь художественная, набор из 5 цветов"
                        },
                        new
                        {
                            Id = new Guid("0122481d-10e3-4b58-89ee-c72269d5c95e"),
                            Cost = 810m,
                            Description = "Краски акварельные для рисования 24 цвета.",
                            Name = "Краска акварель"
                        },
                        new
                        {
                            Id = new Guid("c60de567-a236-4f59-bc76-4aa1109545d6"),
                            Cost = 2000m,
                            Description = "5 цветов, 50 мл.",
                            Name = "Краски акриловые, 5х50 мл"
                        },
                        new
                        {
                            Id = new Guid("37acd775-ee3a-4e6d-83c2-3458adcbf87f"),
                            Cost = 1950m,
                            Description = "Краски масляные художественные для рисования, набор из 10 цветов.",
                            Name = "Набор масляных красок, 10 цветов"
                        },
                        new
                        {
                            Id = new Guid("21b68580-8f57-45a4-a415-1ccfa97337c3"),
                            Cost = 750m,
                            Description = "Набор пастели 24 цвета.",
                            Name = "Набор сухой пастели, 24 цвета"
                        },
                        new
                        {
                            Id = new Guid("0bc0cbd7-de40-46bd-8133-59c8a35b2761"),
                            Cost = 910m,
                            Description = "Набор меловой пастели 48 цв.",
                            Name = "Набор меловой пастели"
                        });
                });

            modelBuilder.Entity("OnlineShop.Db.Models.CartItem", b =>
                {
                    b.HasOne("OnlineShop.Db.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId");

                    b.HasOne("OnlineShop.Db.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");

                    b.HasOne("OnlineShop.Db.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId");

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Image", b =>
                {
                    b.HasOne("OnlineShop.Db.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.ImagePainting", b =>
                {
                    b.HasOne("OnlineShop.Db.Models.Painting", "Painting")
                        .WithMany("Images")
                        .HasForeignKey("PaintingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Painting");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Painting", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
